INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'AC');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PA');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RO');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RR');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'TO');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'MA');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PB');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PE');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PI');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RN');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'SE');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'GO');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'MS');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'MT');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'ES');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'MG');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RJ');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'SP');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RS');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'SC');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'AM');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'AP');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'AL');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'BA');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'CE');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PR');
INSERT INTO RM87138.TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO)
	VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'DF');

INSERT INTO RM87138.TB_SPM_TIPO_TELEFONE (ID_TIPO_TELEFONE,FL_ATIVO,DH_CRIACAO,NM_TIPO_TELEFONE)
	VALUES (SEQ_SPM_TIPO_TELEFONE.nextval,1,SYSDATE,'Residencial');
INSERT INTO RM87138.TB_SPM_TIPO_TELEFONE (ID_TIPO_TELEFONE,FL_ATIVO,DH_CRIACAO,NM_TIPO_TELEFONE)
	VALUES (SEQ_SPM_TIPO_TELEFONE.nextval,1,SYSDATE,'Celular');
INSERT INTO RM87138.TB_SPM_TIPO_TELEFONE (ID_TIPO_TELEFONE,FL_ATIVO,DH_CRIACAO,NM_TIPO_TELEFONE)
	VALUES (SEQ_SPM_TIPO_TELEFONE.nextval,1,SYSDATE,'Fax');
INSERT INTO RM87138.TB_SPM_TIPO_TELEFONE (ID_TIPO_TELEFONE,FL_ATIVO,DH_CRIACAO,NM_TIPO_TELEFONE)
	VALUES (SEQ_SPM_TIPO_TELEFONE.nextval,1,SYSDATE,'Comercial');

INSERT INTO RM87138.TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS)
	VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Em andamento');
INSERT INTO RM87138.TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS)
	VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Temporário');
INSERT INTO RM87138.TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS)
	VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Disparar');
INSERT INTO RM87138.TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS)
	VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Desativado');

-- Auto-generated SQL script #202205180829
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Afeganistão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'África do Sul');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Albânia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Alemanha');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Andorra');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Angola');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Antígua e Barbuda');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Arábia Saudita');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Argélia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Argentina');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Armênia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Aruba');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Austrália');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Áustria');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Azerbaijão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bahamas');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bahrain');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bangladesh');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Barbados');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Belarus');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bélgica');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Belize');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Benin');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bermudas');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bolívia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bósnia e Herzegovina');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Botsuana');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Brasil');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Brunei Darussalam');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bulgária');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Burkina Faso');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Burundi');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Butão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cabo Verde');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Camarões');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Camboja');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Canadá');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Catar');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cazaquistão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Chade');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Chile');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'China');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Chipre');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cingapura');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cisjordânia e Gaza');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Colômbia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Comores');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Congo, Rep. Dem');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Congo, Rep.');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Coreia, Dem. Rep. Popular');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Coreia, Rep.');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Costa do Marfim');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Costa Rica');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Croácia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cuba');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Curaçao');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Dinamarca');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Djibouti');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Dominica');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Egito, Rep. Árabe');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'El Salvador');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Emirados Árabes Unidos');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Equador');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Eritréia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Eslovênia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Espanha');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Estados Unidos');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Estônia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Eswatini');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Etiópia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Federação Russa');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Fiji');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Filipinas');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Finlândia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'França');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gabão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gâmbia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gana');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Geórgia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gibraltar');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Granada');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Grécia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gronelândia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guam');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guatemala');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guiana');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guiné');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guiné Equatorial');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guiné-Bissau');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Haiti');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Honduras');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Hong Kong SAR, China');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Hungria');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Iêmen, Rep.');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilha de Man');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Cayman');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas do Canal');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'ilhas Faroe');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Marianas do Norte');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Marshall');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Salomão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Turks e Caicos');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Virgens (EUA)');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Virgens Britânicas');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Índia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Indonésia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ir');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Irã, Rep. Islâmica');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Iraque');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Irlanda');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Islândia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Israel');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Itália');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Jamaica');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Japão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Jordânia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Kiribati');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Kosovo');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Kuwait');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Laos, PDR');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Lesoto');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Letônia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Líbano');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Libéria');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Líbia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Liechtenstein');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Lituânia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Luxemburgo');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Macedônia, ARJ');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Madagáscar');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Malásia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Malaui');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Maldivas');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Mali');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Malta');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Marrocos');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Maurício');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Mauritânia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'México');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Micronésia, Est. Fed.');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Moçambique');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Moldávia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Mônaco');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Mongólia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Montenegro');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Myanmar');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Namíbia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nauru');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nepal');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nicarágua');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Níger');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nigéria');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Noruega');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nova Caledônia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nova Zelândia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Omã');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Países Baixos');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Palau');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Panamá');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Papua Nova Guiné');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Paquistão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Paraguai');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Peru');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Peru');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Polinésia Francesa');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Polônia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Porto Rico');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Portugal');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Quênia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Região Administrativa Especial de Macau, China');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Reino Unido');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Árabe da Síria');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Centro-Africana');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Checa');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República do Quirguizistão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Dominicana');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Eslovaca');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Romania');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ruanda');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Samoa');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Samoa Americana');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'San Marino');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Santa Lúcia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'São Cristóvão e Névis');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'São Tomé e Príncipe');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'São Vicente e Granadinas');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Senegal');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Serra Leoa');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sérvia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Seychelles');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sint Maarten (parte holandesa)');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Somália');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sri Lanka');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'St. Martin (parte francesa)');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sudão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sudão do Sul');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Suécia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Suíça');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Suriname');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tailândia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tajiquistão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tanzânia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Timor-Leste');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tonga');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Trinidad e Tobago');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tunísia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Turcomenistão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tuvalu');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ucrânia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Uganda');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Uruguai');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Uzbequistão');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Vanuatu');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Venezuela');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Vietnã');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Zâmbia');
INSERT INTO RM87138.TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS)
	VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Zimbábue');

INSERT INTO RM87138.TB_SPM_GRUPO (ID_GRUPO,FL_ATIVO,DH_CRIACAO,NM_GRUPO)
	VALUES (SEQ_SPM_GRUPO.nextval,1,SYSDATE,'Master');
INSERT INTO RM87138.TB_SPM_GRUPO (ID_GRUPO,FL_ATIVO,DH_CRIACAO,NM_GRUPO)
	VALUES (SEQ_SPM_GRUPO.nextval,1,SYSDATE,'Administrador');
INSERT INTO RM87138.TB_SPM_GRUPO (ID_GRUPO,FL_ATIVO,DH_CRIACAO,NM_GRUPO)
	VALUES (SEQ_SPM_GRUPO.nextval,1,SYSDATE,'Lojista');
INSERT INTO RM87138.TB_SPM_GRUPO (ID_GRUPO,FL_ATIVO,DH_CRIACAO,NM_GRUPO)
	VALUES (SEQ_SPM_GRUPO.nextval,1,SYSDATE,'Consumidor');

INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000001',SYSDATE,'Produto 1',100,10.20);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000002',SYSDATE,'Produto 2',150,1530.0);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000003',SYSDATE,'Produto 3',100,20.01);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000004',SYSDATE,'Produto 4',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000005',SYSDATE,'Produto 5',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000006',SYSDATE,'Produto 6',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000007',SYSDATE,'Produto 7',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000008',SYSDATE,'Produto 8',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000009',SYSDATE,'Produto 9',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000010',SYSDATE,'Produto 10',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000011',SYSDATE,'Produto 11',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000012',SYSDATE,'Produto 12',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000013',SYSDATE,'Produto 13',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000014',SYSDATE,'Produto 14',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000015',SYSDATE,'Produto 15',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000016',SYSDATE,'Produto 16',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000017',SYSDATE,'Produto 17',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000018',SYSDATE,'Produto 18',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000019',SYSDATE,'Produto 19',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000020',SYSDATE,'Produto 20',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000021',SYSDATE,'Produto 21',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000022',SYSDATE,'Produto 22',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000023',SYSDATE,'Produto 23',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000024',SYSDATE,'Produto 24',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000025',SYSDATE,'Produto 25',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000026',SYSDATE,'Produto 26',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000027',SYSDATE,'Produto 27',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000028',SYSDATE,'Produto 28',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000029',SYSDATE,'Produto 29',100,50);
INSERT INTO RM87138.TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR)
	VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000030',SYSDATE,'Produto 30',100,50);


FALTA
TB_SPM_USUARIO
TB_SPM_ENDERECO
TB_SPM_TELEFONE
TB_SPM_CONTROLE_EMAIL
TB_SPM_CARRINHO
