INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Afeganistão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'África do Sul');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Albânia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Alemanha');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Andorra');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Angola');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Antígua e Barbuda');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Arábia Saudita');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Argélia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Argentina');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Armênia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Aruba');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Austrália');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Áustria');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Azerbaijão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bahamas');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bahrain');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bangladesh');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Barbados');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Belarus');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bélgica');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Belize');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Benin');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bermudas');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bolívia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bósnia e Herzegovina');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Botsuana');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Brasil');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Brunei Darussalam');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Bulgária');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Burkina Faso');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Burundi');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Butão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cabo Verde');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Camarões');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Camboja');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Canadá');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Catar');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cazaquistão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Chade');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Chile');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'China');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Chipre');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cingapura');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cisjordânia e Gaza');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Colômbia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Comores');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Congo, Rep. Dem');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Congo, Rep.');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Coreia, Dem. Rep. Popular');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Coreia, Rep.');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Costa do Marfim');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Costa Rica');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Croácia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Cuba');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Curaçao');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Dinamarca');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Djibouti');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Dominica');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Egito, Rep. Árabe');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'El Salvador');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Emirados Árabes Unidos');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Equador');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Eritréia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Eslovênia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Espanha');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Estados Unidos');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Estônia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Eswatini');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Etiópia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Federação Russa');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Fiji');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Filipinas');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Finlândia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'França');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gabão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gâmbia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gana');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Geórgia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gibraltar');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Granada');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Grécia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Gronelândia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guam');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guatemala');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guiana');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guiné');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guiné Equatorial');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Guiné-Bissau');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Haiti');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Honduras');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Hong Kong SAR, China');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Hungria');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Iêmen, Rep.');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilha de Man');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Cayman');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas do Canal');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'ilhas Faroe');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Marianas do Norte');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Marshall');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Salomão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Turks e Caicos');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Virgens (EUA)');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ilhas Virgens Britânicas');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Índia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Indonésia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ir');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Irã, Rep. Islâmica');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Iraque');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Irlanda');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Islândia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Israel');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Itália');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Jamaica');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Japão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Jordânia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Kiribati');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Kosovo');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Kuwait');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Laos, PDR');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Lesoto');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Letônia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Líbano');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Libéria');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Líbia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Liechtenstein');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Lituânia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Luxemburgo');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Macedônia, ARJ');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Madagáscar');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Malásia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Malaui');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Maldivas');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Mali');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Malta');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Marrocos');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Maurício');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Mauritânia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'México');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Micronésia, Est. Fed.');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Moçambique');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Moldávia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Mônaco');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Mongólia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Montenegro');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Myanmar');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Namíbia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nauru');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nepal');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nicarágua');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Níger');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nigéria');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Noruega');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nova Caledônia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Nova Zelândia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Omã');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Países Baixos');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Palau');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Panamá');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Papua Nova Guiné');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Paquistão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Paraguai');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Peru');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Peru');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Polinésia Francesa');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Polônia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Porto Rico');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Portugal');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Quênia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Região Administrativa Especial de Macau, China');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Reino Unido');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Árabe da Síria');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Centro-Africana');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Checa');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República do Quirguizistão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Dominicana');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'República Eslovaca');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Romania');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ruanda');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Samoa');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Samoa Americana');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'San Marino');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Santa Lúcia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'São Cristóvão e Névis');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'São Tomé e Príncipe');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'São Vicente e Granadinas');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Senegal');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Serra Leoa');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sérvia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Seychelles');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sint Maarten (parte holandesa)');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Somália');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sri Lanka');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'St. Martin (parte francesa)');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sudão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Sudão do Sul');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Suécia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Suíça');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Suriname');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tailândia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tajiquistão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tanzânia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Timor-Leste');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tonga');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Trinidad e Tobago');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tunísia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Turcomenistão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Tuvalu');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Ucrânia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Uganda');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Uruguai');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Uzbequistão');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Vanuatu');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Venezuela');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Vietnã');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Zâmbia');
INSERT INTO TB_SPM_PAIS (ID_PAIS,FL_ATIVO,DH_CRIACAO,NM_PAIS) VALUES (SEQ_SPM_PAIS.nextval,1,SYSDATE,'Zimbábue');

INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'AC', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PA', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RO', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RR', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'TO', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'MA', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PB', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PE', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PI', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RN', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'SE', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'GO', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'MS', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'MT', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'ES', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'MG', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RJ', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'SP', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'RS', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'SC', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'AM', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'AP', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'AL', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'BA', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'CE', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'PR', 28);
INSERT INTO TB_SPM_ESTADO (ID_ESTADO,FL_ATIVO,DH_CRIACAO,NM_ESTADO, ID_PAIS) VALUES (SEQ_SPM_ESTADO.nextval,1,SYSDATE,'DF', 28);

INSERT INTO TB_SPM_TIPO_TELEFONE (ID_TIPO_TELEFONE,FL_ATIVO,DH_CRIACAO,NM_TIPO_TELEFONE) VALUES (SEQ_SPM_TIPO_TELEFONE.nextval,1,SYSDATE,'Residencial');
INSERT INTO TB_SPM_TIPO_TELEFONE (ID_TIPO_TELEFONE,FL_ATIVO,DH_CRIACAO,NM_TIPO_TELEFONE) VALUES (SEQ_SPM_TIPO_TELEFONE.nextval,1,SYSDATE,'Celular');
INSERT INTO TB_SPM_TIPO_TELEFONE (ID_TIPO_TELEFONE,FL_ATIVO,DH_CRIACAO,NM_TIPO_TELEFONE) VALUES (SEQ_SPM_TIPO_TELEFONE.nextval,1,SYSDATE,'Fax');
INSERT INTO TB_SPM_TIPO_TELEFONE (ID_TIPO_TELEFONE,FL_ATIVO,DH_CRIACAO,NM_TIPO_TELEFONE) VALUES (SEQ_SPM_TIPO_TELEFONE.nextval,1,SYSDATE,'Comercial');

INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Em andamento');
INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Temporário');
INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'E-mail - Disparar');
INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'E-mail - Enviado');
INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Ativo');
INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Desativado');
INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Pago');
INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Recusado');
INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Resetar senha');
INSERT INTO TB_SPM_STATUS (ID_STATUS,DH_CRIACAO,NM_STATUS) VALUES (SEQ_SPM_STATUS.nextval,SYSDATE,'Em andamento resete da senha');

INSERT INTO TB_SPM_GRUPO (ID_GRUPO,FL_ATIVO,DH_CRIACAO,NM_GRUPO) VALUES (SEQ_SPM_GRUPO.nextval,1,SYSDATE,'Master');
INSERT INTO TB_SPM_GRUPO (ID_GRUPO,FL_ATIVO,DH_CRIACAO,NM_GRUPO) VALUES (SEQ_SPM_GRUPO.nextval,1,SYSDATE,'Administrador');
INSERT INTO TB_SPM_GRUPO (ID_GRUPO,FL_ATIVO,DH_CRIACAO,NM_GRUPO) VALUES (SEQ_SPM_GRUPO.nextval,1,SYSDATE,'Lojista');
INSERT INTO TB_SPM_GRUPO (ID_GRUPO,FL_ATIVO,DH_CRIACAO,NM_GRUPO) VALUES (SEQ_SPM_GRUPO.nextval,1,SYSDATE,'Consumidor');

INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000001',SYSDATE,'Produto 1',100,10.20);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000002',SYSDATE,'Produto 2',150,1530.0);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000003',SYSDATE,'Produto 3',100,20.01);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000004',SYSDATE,'Produto 4',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000005',SYSDATE,'Produto 5',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000006',SYSDATE,'Produto 6',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000007',SYSDATE,'Produto 7',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000008',SYSDATE,'Produto 8',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000009',SYSDATE,'Produto 9',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000010',SYSDATE,'Produto 10',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000011',SYSDATE,'Produto 11',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000012',SYSDATE,'Produto 12',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000013',SYSDATE,'Produto 13',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000014',SYSDATE,'Produto 14',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000015',SYSDATE,'Produto 15',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000016',SYSDATE,'Produto 16',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000017',SYSDATE,'Produto 17',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000018',SYSDATE,'Produto 18',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000019',SYSDATE,'Produto 19',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000020',SYSDATE,'Produto 20',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000021',SYSDATE,'Produto 21',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000022',SYSDATE,'Produto 22',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000023',SYSDATE,'Produto 23',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000024',SYSDATE,'Produto 24',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000025',SYSDATE,'Produto 25',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000026',SYSDATE,'Produto 26',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000027',SYSDATE,'Produto 27',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000028',SYSDATE,'Produto 28',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000029',SYSDATE,'Produto 29',100,50);
INSERT INTO TB_SPM_PRODUTO (ID_PRODUTO,FL_ATIVO,DS_CODIGO,DH_CRIACAO,NM_PRODUTO,NR_QTD_ESTOQUE,NR_VALOR) VALUES (SEQ_SPM_PRODUTO.nextval,1,'00000030',SYSDATE,'Produto 30',100,50);

INSERT INTO RM87138.TB_SPM_USUARIO (ID_USUARIO, NM_NOME, NM_SOBRENOME, DS_LOGIN, DS_SENHA, DS_EMAIL, ID_GRUPO, ID_STATUS, DH_CRIACAO) VALUES (1, 'Filipe', 'Holanda', 'filipeholanda', '1234', 'filipe@email.com', 1, 5, SYSDATE);

INSERT INTO RM87138.TB_SPM_CARRINHO (ID_CARRINHO,ID_PRODUTO,ID_STATUS,ID_USUARIO,CD_PEDIDO) VALUES (SEQ_SPM_CARRINHO.NEXTVAL,1,2,1,'00001');
INSERT INTO RM87138.TB_SPM_CARRINHO (ID_CARRINHO,ID_PRODUTO,ID_STATUS,ID_USUARIO,CD_PEDIDO) VALUES (SEQ_SPM_CARRINHO.NEXTVAL,2,2,1,'00001');
INSERT INTO RM87138.TB_SPM_CARRINHO (ID_CARRINHO,ID_PRODUTO,ID_STATUS,ID_USUARIO,CD_PEDIDO) VALUES (SEQ_SPM_CARRINHO.NEXTVAL,3,2,1,'00001');

CREATE OR REPLACE PROCEDURE RM87138.produto_carrinho_adicionar(p_cd_pedido IN VARCHAR2, p_id_usuario IN NUMBER, p_id_produto IN  NUMBER, p_quantidade IN  NUMBER) AS
    PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
    -- Incluir produto na tabela de Carrinho com status "Temporário"
	INSERT INTO RM87138.TB_SPM_CARRINHO (ID_CARRINHO,ID_PRODUTO,ID_STATUS,ID_USUARIO,CD_PEDIDO)
    VALUES (SEQ_SPM_CARRINHO.NEXTVAL,p_id_produto, 2, p_id_usuario, p_cd_pedido);
END;

CREATE OR REPLACE PROCEDURE RM87138.produto_controle_estoque(p_cd_pedido IN VARCHAR2) AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    -- Buscar todos registros do carrinho através pelo parametro código de Pedido com status "Em andamento"
    CURSOR curCarrinho IS
        SELECT
            tsc.ID_PRODUTO,
            tsc.NR_QUANTIDADE
        FROM
            TB_SPM_CARRINHO tsc
        WHERE
            tsc.CD_PEDIDO = p_cd_pedido
        AND tsc.ID_STATUS = 1; -- EM ANDAMENTO

    -- Variavéis
    v_ID_PRODUTO varchar2(100);
    v_NR_QUANTIDADE NUMBER(19,0);

BEGIN

    -- Abrir cursor da consulta
	OPEN curCarrinho;

	-- Percorrer todos registros, conforme da consulta
	LOOP
	    FETCH  curCarrinho INTO v_ID_PRODUTO, v_NR_QUANTIDADE;
		EXIT WHEN curCarrinho%NOTFOUND;
			-- Alterar a quantidade de estoque do produto
			UPDATE
				RM87138.TB_SPM_PRODUTO
			SET
				NR_QTD_ESTOQUE = NR_QTD_ESTOQUE - v_NR_QUANTIDADE
			WHERE
				ID_PRODUTO = v_ID_PRODUTO;
			COMMIT;
	END LOOP;

	-- Fechar cursor da consulta
	CLOSE curCarrinho;

	-- Mudar o status para "Pago", ou seja, foi processado e não há necessidade de entrar novamente no processo, caso seja chamado com mesmo pedido
	UPDATE
		RM87138.TB_SPM_CARRINHO
	SET
		ID_STATUS = 7 -- Pago
	WHERE
		CD_PEDIDO = p_cd_pedido;
	COMMIT;
END;


CREATE OR REPLACE PROCEDURE RM87138.produto_carrinho_pagamento(p_cd_pedido IN VARCHAR2) AS
    PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
    -- Mudar o status para "Em andamento" de todos registros relacionado ao código do pedido
	UPDATE RM87138.TB_SPM_CARRINHO
	SET ID_STATUS =  1 -- EM ANDAMENTO
	WHERE CD_PEDIDO = p_cd_pedido;
	COMMIT;
END;

CREATE OR REPLACE PROCEDURE RM87138.resetar_senha(p_id_usuario IN NUMBER) AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    -- Variavéis
    v_email varchar2(100);

  BEGIN

    -- Resetar a senha de forma alertório do usuário e setar status para "Em andamento resete da senha"
	UPDATE
		RM87138.TB_SPM_USUARIO
	SET
		DS_SENHA = dbms_random.value(),
		ID_STATUS = 10 -- Em andamento resete da senha
	WHERE
		ID_USUARIO = p_id_usuario;
	COMMIT;

    -- Capturar a informação e-mail do usuário
	SELECT
		DS_EMAIL INTO v_email
	FROM
		RM87138.TB_SPM_USUARIO
	WHERE
		ID_USUARIO = p_id_usuario;

	-- Incluir na tabela de controle Email com status "Disparar"
	-- Obs.: Existe um JOB que pegará todos registros que estão na fila com status "Disparar" e serão disparados
	INSERT INTO TB_SPM_CONTROLE_EMAIL(ID_CONTROLE_EMAIL, DS_EMAIL, STATUS_ID, DH_CRIACAO)
	VALUES(SEQ_SPM_CONTROLE_EMAIL.NEXTVAL, v_email, 3, SYSDATE);
	COMMIT;

END;

CREATE OR REPLACE PROCEDURE RM87138.usuario_ausente AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    -- Variavéis
    p_id_usuario number(19,0);

BEGIN

	-- Mudar o status para "Desativado" do usuário
	UPDATE
		RM87138.TB_SPM_USUARIO
	SET
		ID_STATUS = 6 -- DESATIVADO
	WHERE
		ID_USUARIO = p_id_usuario;
	COMMIT;

END;

CREATE OR REPLACE PROCEDURE RM87138.usuario_morto AS
    PRAGMA AUTONOMOUS_TRANSACTION;

    -- Variavéis
    p_id_usuario number(19,0);

BEGIN

    -- Excluir todos registros de Carrinho relacionado através pelo parametro de id usuario
	DELETE FROM
		RM87138.TB_SPM_CARRINHO
	WHERE
		ID_USUARIO = p_id_usuario;
	COMMIT;

    -- Excluir todos registros de Endereco relacionado através pelo parametro de id usuario
	DELETE FROM
		RM87138.TB_SPM_ENDERECO
	WHERE
		ID_USUARIO = p_id_usuario;
	COMMIT;

    -- Excluir todos registros de Telefone relacionado através pelo parametro de id usuario
	DELETE FROM
		RM87138.TB_SPM_TELEFONE
	WHERE
		ID_USUARIO = p_id_usuario;
	COMMIT;

    -- Excluir todos registros de Usuario relacionado através pelo parametro de id usuario
	DELETE FROM
		RM87138.TB_SPM_USUARIO
	WHERE
		ID_USUARIO = p_id_usuario;
	COMMIT;

END;
